config/routes.rb
Rails.application.routes.draw do
  get 'tutorial/setumei'

  get 'tutorial/sonota'

  resources :jimotalks
  resources :reviews
  resources :local_infos
  resources :minnpakus
  root 'minnpakus#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jimotalk.rb
class Jimotalk < ApplicationRecord
  belongs_to :local_info
end

app/controllers/jimotalks_controller.rb
class JimotalksController < ApplicationController
  before_action :set_jimotalk, only: [:show, :edit, :update, :destroy]

  # GET /jimotalks
  # GET /jimotalks.json
  def index
    @jimotalks = Jimotalk.all
  end

  # GET /jimotalks/1
  # GET /jimotalks/1.json
  def show
  end

  # GET /jimotalks/new
  def new
    @jimotalk = Jimotalk.new
  end

  # GET /jimotalks/1/edit
  def edit
  end

  # POST /jimotalks
  # POST /jimotalks.json
  def create
    @jimotalk = Jimotalk.new(jimotalk_params)
    @local_info = LocalInfo.find(@jimotalk.local_info_id)
    respond_to do |format|
      if @jimotalk.save
        format.html { redirect_to @local_info, notice: 'Jimotalk was successfully created.' }
        format.json { render :show, status: :created, location: @jimotalk }
      else
        format.html { render :new }
        format.json { render json: @jimotalk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jimotalks/1
  # PATCH/PUT /jimotalks/1.json
  def update
    respond_to do |format|
      if @jimotalk.update(jimotalk_params)
        format.html { redirect_to @jimotalk, notice: 'Jimotalk was successfully updated.' }
        format.json { render :show, status: :ok, location: @jimotalk }
      else
        format.html { render :edit }
        format.json { render json: @jimotalk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jimotalks/1
  # DELETE /jimotalks/1.json
  def destroy
    @jimotalk.destroy
    respond_to do |format|
      format.html { redirect_to jimotalks_url, notice: 'Jimotalk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jimotalk
      @jimotalk = Jimotalk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jimotalk_params
      params.require(:jimotalk).permit(:local_info_id, :body, :hyouka)
    end
end

app/helpers/jimotalks_helper.rb
module JimotalksHelper
end

app/views/jimotalks/_form.html.erb
<%= form_with(model: jimotalk, local: true) do |form| %>
  <% if jimotalk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jimotalk.errors.count, "error") %> prohibited this jimotalk from being saved:</h2>

      <ul>
      <% jimotalk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :local_info_id %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :jimotalk_body %>
  </div>

  <div>
    <%= form.label :hyouka %>
    <%= form.number_field :hyouka, id: :jimotalk_hyouka %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jimotalks/edit.html.erb
<h1>Editing Jimotalk</h1>

<%= render 'form', jimotalk: @jimotalk %>

<%= link_to 'Show', @jimotalk %> |
<%= link_to 'Back', jimotalks_path %>

app/views/jimotalks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jimotalks</h1>

<table>
  <thead>
    <tr>
      <th>Local info</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jimotalks.each do |jimotalk| %>
      <tr>
        <td><%= jimotalk.local_info_id %></td>
        <td><%= jimotalk.body %></td>
        <td><%= link_to 'Show', jimotalk %></td>
        <td><%= link_to 'Edit', edit_jimotalk_path(jimotalk) %></td>
        <td><%= link_to 'Destroy', jimotalk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jimotalk', new_jimotalk_path %>

app/views/jimotalks/new.html.erb
<h1>New Jimotalk</h1>

<%= render 'form', jimotalk: @jimotalk %>

<%= link_to 'Back', jimotalks_path %>

app/views/jimotalks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Local info:</strong>
  <%= @jimotalk.local_info_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @jimotalk.body %>
</p>