config/routes.rb
Rails.application.routes.draw do
  get 'tutorial/setumei'

  get 'tutorial/sonota'

  resources :jimotalks
  resources :reviews
  resources :local_infos
  resources :minnpakus
  root 'minnpakus#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/minnpaku.rb
class Minnpaku < ApplicationRecord

  mount_uploader :image, ImageUploader
  has_many :reviews
  has_many :minnpaku_local_infos
  has_many :local_infos, through: :minnpaku_local_infos
end

app/controllers/minnpakus_controller.rb
class MinnpakusController < ApplicationController
  before_action :set_minnpaku, only: [:show, :edit, :update, :destroy]

  # GET /minnpakus
  # GET /minnpakus.json
  def index
    @minnpakus = Minnpaku.all
  end

  # GET /minnpakus/1
  # GET /minnpakus/1.json
  def show
    @minnpaku = Minnpaku.find(params[:id])
    @reviews = @minnpaku.reviews.all
    @review = @minnpaku.reviews.build
    @review_ave = @reviews.average(:hyouka)
    @local_infos = @minnpaku.local_infos
  end

  # GET /minnpakus/new
  def new
    @minnpaku = Minnpaku.new
  end

  # GET /minnpakus/1/edit
  def edit
  end

  # POST /minnpakus
  # POST /minnpakus.json
  def create
    @minnpaku = Minnpaku.new(minnpaku_params)

    respond_to do |format|
      if @minnpaku.save
        format.html { redirect_to @minnpaku, notice: 'Minnpaku was successfully created.' }
        format.json { render :show, status: :created, location: @minnpaku }
      else
        format.html { render :new }
        format.json { render json: @minnpaku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minnpakus/1
  # PATCH/PUT /minnpakus/1.json
  def update
    respond_to do |format|
      if @minnpaku.update(minnpaku_params)
        format.html { redirect_to @minnpaku, notice: 'Minnpaku was successfully updated.' }
        format.json { render :show, status: :ok, location: @minnpaku }
      else
        format.html { render :edit }
        format.json { render json: @minnpaku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minnpakus/1
  # DELETE /minnpakus/1.json
  def destroy
    @minnpaku.destroy
    respond_to do |format|
      format.html { redirect_to minnpakus_url, notice: 'Minnpaku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minnpaku
      @minnpaku = Minnpaku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minnpaku_params
      params.require(:minnpaku).permit(:name, :body, :image, :price, :performance, :smoke,
      :style, :provide, :please, :review, :latitude, :longitude)
    end
end

app/helpers/minnpakus_helper.rb
module MinnpakusHelper
end

app/views/minnpakus/_form.html.erb
<%= form_with(model: minnpaku, local: true) do |form| %>
  <% if minnpaku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(minnpaku.errors.count, "error") %> prohibited this minnpaku from being saved:</h2>

      <ul>
      <% minnpaku.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plase_name %>
    <%= form.text_field :name, id: :minnpaku_name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :minnpaku_body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :minnpaku_image %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :minnpaku_price %>
  </div>

  <div class="field">
    <%= form.label :performance %>
    <%= form.text_field :performance, id: :minnpaku_performance %>
  </div>

  <div class="field">
    <%= form.label :smoke %>
    <%= form.text_field :smoke, id: :minnpaku_smoke %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style, id: :minnpaku_style %>
  </div>

  <div class="field">
    <%= form.label :provide %>
    <%= form.text_area :provide, id: :minnpaku_provide %>
  </div>

  <div class="field">
    <%= form.label :please %>
    <%= form.text_area :please, id: :minnpaku_please %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :minnpaku_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :minnpaku_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/minnpakus/edit.html.erb
<h1>Editing Minnpaku</h1>

<%= render 'form', minnpaku: @minnpaku %>

<%= link_to 'Show', @minnpaku %> |
<%= link_to 'Back', minnpakus_path %>

app/views/minnpakus/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= image_tag("https://takineru.s3-ap-northeast-1.amazonaws.com/title_image/20663551_1045676178901715_51522057_o.jpg", :style => "width: 250px;") %></h1>
<div class="col-md-6">

  <% @minnpakus.each do |minnpaku| %>
  <%= link_to(minnpaku, :style => "text-decoration:none;") do %>
  <ul class="list-inline" align = "left" >
    <li><%= image_tag(minnpaku.image, :class => "card-img-show", :style => "width: 100px;display: inline-block;", :alt => "") %></li>
    <li style="font-size: 22px; font-weight: bold;">【<%= minnpaku.body %>】<%= minnpaku.name %></li>
  </ul>
  <p><%= minnpaku.please %></p>
  <% end %>
  <div style="border-bottom: 2px solid #D7D8D8; margin: 3px 0px 6px 0px; border-radius: 5px 5px 5px 5px;"></div>
  <% end %>
</div>

<div class="col-md-6">
<div id="map"></div>
<style type="text/css">
  #map { height:700px; width: 600px; border-radius: 5px;box-shadow: 0 2px 5px #ccc;}
  .leaflet-marker-icon-color-gray  { -webkit-filter: grayscale(100%); filter: grayscale(100%); }
  .leaflet-marker-icon-color-blue  { -webkit-filter: hue-rotate(-270deg); filter: hue-rotate(-9deg); }
</style>
<script type="text/javascript">
    L.Icon.Default.imagePath = "https://takineru.s3-ap-northeast-1.amazonaws.com/image/";
    var map = L.map('map').setView([39.778707, 141.108164],11.5);
    var osmUrl = "http://tile.openstreetmap.jp/{z}/{x}/{y}.png";
    var osmAttrib = "Map data &COPY; OpenStreetMap contributors";
    L.tileLayer(osmUrl, {
        attribution: osmAttrib,
        maxZoom: 13,
    }).addTo(map);

</script>
<% @minnpakus.each do |shop| %>
    <script type="text/javascript">
        var popup = L.popup().setContent('<div class="map-title"><%= shop.name %></div><%= image_tag(shop.image,:size => "86×86", :class => "map-img", :alt => "") %><p style="width: 200px;"></p><%= button_to "民泊詳細へ", minnpaku_path(shop.id), :method => :get , :class => "btn btn-info btn-xs" %>');
        var marker = L.marker(
            [<%= shop.latitude %>,<%= shop.longitude %>],
            { name: map.name }
        ).addTo(map).bindPopup(popup);
          L.DomUtil.addClass( marker._icon, "leaflet-marker-icon-color-blue")
    </script>
<% end %>
</div>

app/views/minnpakus/new.html.erb
<h1>New Minnpaku</h1>

<%= render 'form', minnpaku: @minnpaku %>

<%= link_to 'Back', minnpakus_path %>

app/views/minnpakus/show.html.erb
<p id="notice"><%= notice %></p>

<p style="font-size: 22px; mergin-bottom: 20px;">
  <strong>Place_Name:</strong>
  <%= @minnpaku.name %>
</p>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <p>
        <strong>Image:</strong>
        <%= image_tag(@minnpaku.image, :class => "card-img-show", :alt => "") %>
      </p>
    </div>

    <div class="col-md-4" style="padding: 20px 0px 20px 0px;">
      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Price:</strong>
        <%= @minnpaku.price %>
      </p>

      <p style="font-size: 17px;; margin: 10px 0px">
        <strong>Performance:</strong>
        <%= @minnpaku.performance %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Smoke:</strong>
        <% if @minnpaku.smoke == true then%>
        喫煙
        <% else %>
        禁煙
        <% end %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Style:</strong>
        <%= @minnpaku.style %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Provide:</strong>
        <%= @minnpaku.provide %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Please:</strong>
        <%= @minnpaku.please %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Review:</strong>
        <%= @review_ave %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Latitude:</strong>
        <%= @minnpaku.latitude %>
      </p>

      <p style="font-size: 17px; margin: 10px 0px">
        <strong>Longitude:</strong>
        <%= @minnpaku.longitude %>
      </p>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
<div class="col-md-4">
  <% @reviews.each do |review| %>
  <div>
    <p><%= review.body %></p>
    <p><%= review.hyouka %></p>
  </div>
  <% end %>
  <%= render 'reviews/form' , review: @review%>
</div>

</div>
</div>
<% @local_infos.each do |local_info| %>
<div class="col-md-4">
  <%= local_info.name %>
  <%= link_to(local_info, :style => "text-decoration:none;") do %>
  <%= image_tag(local_info.image, :class => "map-img", :alt => "") %>
  <% end %>
</div>
<% end %>