config/routes.rb
Rails.application.routes.draw do
  get 'tutorial/setumei'

  get 'tutorial/sonota'

  resources :jimotalks
  resources :reviews
  resources :local_infos
  resources :minnpakus
  root 'minnpakus#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Takineru</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style type="text/css">
  body {
    <% if @tutorial_flag.present? then %>
    padding-top: 400px;
    <% elsif %>
    padding-top: 80px;
    <% end %>
  }
  @media ( min-width: 768px ) {
    #banner {
      min-height: 300px;
      border-bottom: none;
    }
    .bs-docs-section {
      margin-top: 8em;
    }
    .bs-component {
      position: relative;
    }
    .bs-component .modal {
      position: relative;
      top: auto;
      right: auto;
      left: auto;
      bottom: auto;
      z-index: 1;
      display: block;
    }
    .bs-component .modal-dialog {
      width: 90%;
    }
    .bs-component .popover {
      position: relative;
      display: inline-block;
      width: 220px;
      margin: 20px;
    }
    .nav-tabs {
      margin-bottom: 15px;
    }
    .progress {
      margin-bottom: 10px;
    }
  }
  </style>
</head>
<header>
  <div class="bs-component">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"href="/"><%= image_tag("https://takineru.s3-ap-northeast-1.amazonaws.com/title_image/takineru-aikion.png", :style => "width: 200px;", :class => "aikon") %></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <li><%= link_to  "民宿ページ",minnpakus_path, :class => "link_class"%></li>
            <li><%= link_to  "じもとーく", local_infos_path, :class => "link_class" %></li>
            <li><%= link_to  "TAKI-NERUとは？", tutorial_setumei_path, :class => "link_class" %></li>
            <li><%= link_to  "お問い合わせ", root_path, :class => "link_class" %></li>
          </ul>
        </div>
        <% if @tutorial_flag.present? then %>
        <div style="text-align: center; padding: 20px;font-size: 25px;">
          <%= image_tag("https://takineru.s3-ap-northeast-1.amazonaws.com/title_image/takineru-aikion.png", :style => "width: 300px;") %>とは?
        </div>
        <% end %>
      </div>
    </nav>
  </div>
</header>
<style type="text/css">
body {
  <% if @tutorial_flag.present? then %>
  padding-top: 400px;
  <% elsif %>
  padding-top: 80px;
  <% end %>
}
</style>
<body>
  <div class="container main-container" style="font-family: Helvetica , "游ゴシック" , "Yu Gothic" , sans-serif;">
    <%= yield %>
  </div>
</body>
</html>